### ISSUE TITLE
Suggestion for a polybar module

### ISSUE THREAD

**Issue by cdutsov** [infokiller/i3-workspace-groups#39]
Hello infokiller,
first I would like to thank you for the great tool you've made! I was looking for something like this for a long time!
The only problem is that I didn't like how the workspaces appear in polybar, so I've made a little script to get the following output:
![image](https://user-images.githubusercontent.com/11442558/99852423-426ac080-2b81-11eb-859b-940d6d2f7518.png)
The yellow numbers are on a 2nd screen. I thought that it would be nice to show a shorthand notation for the numbers if there are many consecutive.

The script is this one: https://gitlab.com/cdutsov/dotfiles/-/blob/master/polybar/i3-mod.sh
And it needs to be triggered on changes in the workspaces, so a simple python script can be used to tell that to polybar:
https://gitlab.com/cdutsov/dotfiles/-/blob/master/polybar/i3-pyton.py

And the polybar module can be set up with:
```
[module/i3-mod]
type = custom/ipc
hook-0 = ~/.config/polybar/i3-mod.sh
initial = 1
```
I've been using it for a few days and it seems to be working ok. It can be improved probably, but I thought that it would be nice to share it even like that.

**Comment by infokiller** [comment]
Thanks for sharing @cdutsov that's great!
I actually tried to integrate it into core polybar in the past (see https://github.com/infokiller/i3-workspace-groups/issues/3#issuecomment-447577478 and a prerequisite PR in https://github.com/polybar/polybar/pull/1550), but it was rejected.
For now I maintain a [polybar fork](https://github.com/infokiller/polybar/tree/i3-workspace-groups) with this feature, but I actually prefer your approach, because it will be easier for other people to only install the IPC module instead of building polybar from scratch.
If you're up to it, you can send a PR that adds these changes and I'll be happy to merge it. I will probably need to do some changes to match the project coding style (it can be done after the PR), and I may rewrite it in the future (I'll probably prefer to use Python or Go for the main functionality, and in general I'm considering rewriting the main project in Go to reduce latency).

**Comment by cdutsov** [comment]
Thanks for the suggestion to include the script! I have submitted a PR. I hope its ok because its my first one ever.

In the beginning the script was actually a few lines of bash, but you know how it is... from 2 lines it becomes 3 and from 3 - 4 and before you know it you have a 100+ lines monstrosity and you are pulling `sed` incantations from the deepest pits of hell. 
Right now the script completes in ~150 ms with 4-5 groups with 3-4 windows per group on my i7-7700HQ laptop. It is definitely not perfect and some rewriting could be useful in the future. If I have the time I can try to do it in Python.

**Comment by infokiller** [comment]
Thanks! I ran into issues with Python startup time in i3-workspace-groups (see <https://github.com/infokiller/i3-workspace-groups#limitations>). go/rust is probably the way to go for good performance (and modern tools).
