### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by kharazi** [infokiller/i3-workspace-groups#61]
I was using i3-workspace-groups (thanks to this performance booster tool) with Polybar for day-by-day work and experienced a delay on the Polybar updater script. For example, when I have many groups and workspaces there is a delay in showing active ws on the bar.
As you mentioned [here](https://github.com/infokiller/config-public#general):

> Don't use Python for tools that should launch fast (less than 100ms). Prefer Go in this case. For example, [i3-workspace-groups](https://github.com/infokiller/i3-workspace-groups) was written in Python, which causes some operations to have noticeable latency.

Do you detect any bottleneck in the i3-workspace-groups process? Is there any effort to rewrite it with Go?
I am eager to contribute.

**Comment by infokiller** [comment]
What you describe sounds like an issue with the polybar updater, not the core i3-workspace-groups. Can you please post your full i3 and polybar config, i3-workspace-groups version, etc?

As for the rewrite in go, it's not high priority for now because most of the performance issues are resolved with client-server mode (which is still undocumented, you can track https://github.com/infokiller/i3-workspace-groups/issues/52).
If you want to use it, please let me know and I'll add docs soon
